import type { Provider, Product, Category } from './types';

export const CATEGORIES: { name: Category; icon: string; emoji: string }[] = [
  { name: 'Teaching', icon: 'GraduationCap', emoji: '📚' },
  { name: 'Tailoring', icon: 'Scissors', emoji: '🧵' },
  { name: 'Cooking', icon: 'ChefHat', emoji: '🍳' },
  { name: 'Gardening', icon: 'Sprout', emoji: '🌱' },
  { name: 'Childcare', icon: 'Baby', emoji: '👶' },
  { name: 'Handicrafts', icon: 'Hammer', emoji: '🧶' },
  { name: 'Music', icon: 'Music', emoji: '🎵' },
  { name: 'Languages', icon: 'Languages', emoji: '🗣️' },
  { name: 'Consulting', icon: 'Briefcase', emoji: '💼' },
  { name: 'Beauty', icon: 'Sparkles', emoji: '✨' },
  { name: 'Repairs', icon: 'Wrench', emoji: '🔧' },
  { name: 'Art', icon: 'Palette', emoji: '🎨' },
];

export const AVATARS = [
  'https://images.pexels.com/photos/2204764/pexels-photo-2204764.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  'https://images.pexels.com/photos/3777943/pexels-photo-3777943.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
];

export const PROVIDERS: Provider[] = [
  {
    id: 'p1',
    name: 'Lakshmi Amma',
    age: 62,
    category: 'Cooking',
    skillTitle: 'Home-style South Indian Meals',
    bio: 'I have been cooking traditional meals for over 40 years — idli, dosa, sambar, rasam, and festival sweets. I prepare fresh meals daily using locally sourced ingredients.',
    skills: ['South Indian', 'Tiffin', 'Festival Sweets', 'Pickles', 'Catering (small)'],
    experienceYears: 40,
    rating: 4.9,
    reviews: 128,
    priceFrom: 60,
    distanceKm: 1.2,
    matchScore: 94,
    avatar: AVATARS[0],
    locationArea: 'Jayanagar 4th Block',
    availability: 'Mon–Sat, 7 AM–2 PM',
    languages: ['Kannada', 'Tamil', 'Hindi'],
    verified: true,
    completedJobs: 340,
    responseTime: 'within 1 hour',
  },
  {
    id: 'p2',
    name: 'Ramesh Sharma',
    age: 58,
    category: 'Teaching',
    skillTitle: 'Mathematics Tutor (Class 6–12)',
    bio: 'Retired school teacher with 30 years of mathematics teaching experience. I make concepts simple and build strong foundations. Patient and friendly with nervous students.',
    skills: ['Mathematics', 'Algebra', 'Geometry', 'Exam Prep', 'Logical Reasoning'],
    experienceYears: 30,
    rating: 4.8,
    reviews: 96,
    priceFrom: 250,
    distanceKm: 2.5,
    matchScore: 91,
    avatar: AVATARS[1],
    locationArea: 'BTM Layout',
    availability: 'Mon–Fri, 4 PM–8 PM',
    languages: ['Hindi', 'English', 'Kannada'],
    verified: true,
    completedJobs: 210,
    responseTime: 'within 2 hours',
  },
  {
    id: 'p3',
    name: 'Fatima Begum',
    age: 45,
    category: 'Tailoring',
    skillTitle: 'Custom Tailoring & Alterations',
    bio: 'I stitch salwar suits, blouses, and kids wear with perfect fitting. I also do alterations and embroidery work. 20 years of experience with home pickup and delivery.',
    skills: ['Salwar Suits', 'Blouse Fitting', 'Alterations', 'Embroidery', 'Kids Wear'],
    experienceYears: 20,
    rating: 4.7,
    reviews: 74,
    priceFrom: 150,
    distanceKm: 3.1,
    matchScore: 88,
    avatar: AVATARS[2],
    locationArea: 'Frazer Town',
    availability: 'Daily, 10 AM–7 PM',
    languages: ['Urdu', 'Hindi', 'Kannada'],
    verified: true,
    completedJobs: 180,
    responseTime: 'within 3 hours',
  },
  {
    id: 'p4',
    name: 'Saroja Krishna',
    age: 55,
    category: 'Childcare',
    skillTitle: 'Experienced Nanny & Babysitter',
    bio: 'Caring nanny with 15 years experience looking after children aged 6 months to 8 years. First aid trained. Can help with meals, homework, and bedtime routines.',
    skills: ['Infant Care', 'Toddler Care', 'First Aid', 'Meal Prep', 'Homework Help'],
    experienceYears: 15,
    rating: 4.9,
    reviews: 52,
    priceFrom: 200,
    distanceKm: 4.0,
    matchScore: 86,
    avatar: AVATARS[3],
    locationArea: 'Indiranagar',
    availability: 'Mon–Sat, Flexible',
    languages: ['Tamil', 'English', 'Kannada'],
    verified: true,
    completedJobs: 95,
    responseTime: 'within 1 hour',
  },
  {
    id: 'p5',
    name: 'Gangadhar Rao',
    age: 64,
    category: 'Music',
    skillTitle: 'Carnatic Vocal & Veena Teacher',
    bio: 'I teach Carnatic vocal music and veena to students of all ages. Trained under guru tradition for 45 years. I conduct classes at my home or online.',
    skills: ['Carnatic Vocal', 'Veena', 'Bhajans', 'Devotional Music', 'Music Theory'],
    experienceYears: 45,
    rating: 5.0,
    reviews: 38,
    priceFrom: 400,
    distanceKm: 5.2,
    matchScore: 83,
    avatar: AVATARS[4],
    locationArea: 'Malleshwaram',
    availability: 'Tue, Thu, Sat',
    languages: ['Telugu', 'Kannada', 'Sanskrit'],
    verified: true,
    completedJobs: 60,
    responseTime: 'within 4 hours',
  },
  {
    id: 'p6',
    name: 'Meena Iyer',
    age: 52,
    category: 'Handicrafts',
    skillTitle: 'Handmade Crafts & Gift Items',
    bio: 'I create handmade decorative items, torans, pot painting, and customised gift hampers. Each piece is made with care and traditional techniques.',
    skills: ['Pot Painting', 'Toran Making', 'Gift Hampers', 'Rangoli', 'Decoupage'],
    experienceYears: 18,
    rating: 4.6,
    reviews: 41,
    priceFrom: 120,
    distanceKm: 6.1,
    matchScore: 79,
    avatar: AVATARS[5],
    locationArea: 'JP Nagar',
    availability: 'Mon–Sat, 11 AM–6 PM',
    languages: ['Tamil', 'Kannada', 'Hindi'],
    verified: false,
    completedJobs: 88,
    responseTime: 'within 6 hours',
  },
  {
    id: 'p7',
    name: 'Joseph D\'Souza',
    age: 61,
    category: 'Repairs',
    skillTitle: 'Home Appliance Repair',
    bio: 'Electrician and appliance repair specialist — mixers, fans, geysers, and basic wiring. 35 years of honest, reliable service. No visit charge within 5 km.',
    skills: ['Appliance Repair', 'Wiring', 'Fan Repair', 'Geyser Service', 'Inverter Setup'],
    experienceYears: 35,
    rating: 4.7,
    reviews: 112,
    priceFrom: 100,
    distanceKm: 2.8,
    matchScore: 85,
    avatar: AVATARS[6],
    locationArea: 'Koramangala',
    availability: 'Daily, 9 AM–8 PM',
    languages: ['English', 'Kannada', 'Hindi', 'Tamil'],
    verified: true,
    completedJobs: 510,
    responseTime: 'within 30 min',
  },
  {
    id: 'p8',
    name: 'Kamala Devi',
    age: 49,
    category: 'Gardening',
    skillTitle: 'Kitchen Garden & Terrace Gardening',
    bio: 'I help set up terrace and balcony gardens — vegetables, herbs, and flowering plants. I also provide weekly maintenance and organic compost.',
    skills: ['Terrace Garden', 'Vegetable Growing', 'Composting', 'Plant Care', 'Landscaping (small)'],
    experienceYears: 12,
    rating: 4.8,
    reviews: 29,
    priceFrom: 300,
    distanceKm: 6.5,
    matchScore: 76,
    avatar: AVATARS[7],
    locationArea: 'HSR Layout',
    availability: 'Wed, Fri, Sun',
    languages: ['Kannada', 'Hindi'],
    verified: false,
    completedJobs: 42,
    responseTime: 'within 1 day',
  },
];

const PRODUCT_IMAGES = [
  'https://images.pexels.com/photos/4198015/pexels-photo-4198015.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
  'https://images.pexels.com/photos/4198562/pexels-photo-4198562.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
  'https://images.pexels.com/photos/6102952/pexels-photo-6102952.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
  'https://images.pexels.com/photos/6164019/pexels-photo-6164019.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
  'https://images.pexels.com/photos/6192495/pexels-photo-6192495.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
  'https://images.pexels.com/photos/2637742/pexels-photo-2637742.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
  'https://images.pexels.com/photos/1098390/pexels-photo-1098390.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
  'https://images.pexels.com/photos/2476756/pexels-photo-2476756.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
];

export const PRODUCTS: Product[] = [
  {
    id: 'pr1',
    title: 'Homemade Mysore Pak (500g)',
    category: 'Cooking',
    price: 180,
    rating: 4.9,
    reviews: 64,
    sellerName: 'Lakshmi Amma',
    sellerId: 'p1',
    distanceKm: 1.2,
    image: PRODUCT_IMAGES[0],
    description: 'Traditional ghee Mysore Pak made fresh for festivals. Melt-in-mouth texture, pure ghee.',
    tags: ['Fresh', 'Festival Special', 'Pure Ghee'],
  },
  {
    id: 'pr2',
    title: 'Hand-painted Terracotta Diya Set (6 pcs)',
    category: 'Handicrafts',
    price: 250,
    rating: 4.7,
    reviews: 22,
    sellerName: 'Meena Iyer',
    sellerId: 'p6',
    distanceKm: 6.1,
    image: PRODUCT_IMAGES[1],
    description: 'Beautifully hand-painted terracotta diyas for Diwali and home decor. Set of 6 unique designs.',
    tags: ['Handmade', 'Diwali', 'Decor'],
  },
  {
    id: 'pr3',
    title: 'Custom Embroidered Kurti',
    category: 'Tailoring',
    price: 650,
    rating: 4.8,
    reviews: 18,
    sellerName: 'Fatima Begum',
    sellerId: 'p3',
    distanceKm: 3.1,
    image: PRODUCT_IMAGES[2],
    description: 'Stitched to your measurements with hand embroidery on cotton fabric. Delivery in 7 days.',
    tags: ['Custom Fit', 'Hand Embroidery', 'Cotton'],
  },
  {
    id: 'pr4',
    title: 'Organic Vegetable Seed Kit',
    category: 'Gardening',
    price: 120,
    rating: 4.6,
    reviews: 35,
    sellerName: 'Kamala Devi',
    sellerId: 'p8',
    distanceKm: 6.5,
    image: PRODUCT_IMAGES[3],
    description: '12 varieties of organic vegetable seeds perfect for terrace gardens. Includes growing guide.',
    tags: ['Organic', 'Beginner Friendly', '12 Varieties'],
  },
  {
    id: 'pr5',
    title: 'Ajmeri Pickle Jar (Mango, 400g)',
    category: 'Cooking',
    price: 150,
    rating: 4.9,
    reviews: 51,
    sellerName: 'Lakshmi Amma',
    sellerId: 'p1',
    distanceKm: 1.2,
    image: PRODUCT_IMAGES[4],
    description: 'Spicy homemade mango pickle with traditional Ajmeri masala. No preservatives.',
    tags: ['Homemade', 'No Preservatives', 'Spicy'],
  },
  {
    id: 'pr6',
    title: 'Handwoven Toran (Door Hanging)',
    category: 'Handicrafts',
    price: 200,
    rating: 4.5,
    reviews: 14,
    sellerName: 'Meena Iyer',
    sellerId: 'p6',
    distanceKm: 6.1,
    image: PRODUCT_IMAGES[5],
    description: 'Colourful handwoven toran for door decoration. 4 feet length, traditional designs.',
    tags: ['Handwoven', 'Door Decor', 'Traditional'],
  },
  {
    id: 'pr7',
    title: 'Watercolour Painting (Landscape, A3)',
    category: 'Art',
    price: 800,
    rating: 5.0,
    reviews: 9,
    sellerName: 'Gangadhar Rao',
    sellerId: 'p5',
    distanceKm: 5.2,
    image: PRODUCT_IMAGES[6],
    description: 'Original watercolour landscape painting on A3 handmade paper. Framed.',
    tags: ['Original', 'Framed', 'One of a Kind'],
  },
  {
    id: 'pr8',
    title: 'Natural Skincare Gift Hamper',
    category: 'Beauty',
    price: 450,
    rating: 4.7,
    reviews: 27,
    sellerName: 'Saroja Krishna',
    sellerId: 'p4',
    distanceKm: 4.0,
    image: PRODUCT_IMAGES[7],
    description: 'Herbal face pack, rose water, and handmade soap gift set. All natural ingredients.',
    tags: ['Natural', 'Gift Set', 'Herbal'],
  },
];
